#!/bin/sh /etc/rc.common

START=12
USE_PROCD=1
NAME=iw-telemetry
PROG=/usr/bin/iw-telemetry

start_service() {
    config_load iw-telemetry

    config_foreach start_instance wifi-device
}

start_instance() {
    local cfg="$1"
    local iface output_type dest_ip dest_port endpoint mode hostname_tag interval count no_compress

    logger -t iw-telemetry "loading instance $1"

    config_get iface "$cfg" device
    config_get output_type "$cfg" output_type
    config_get dest_ip "$cfg" dest_ip
    config_get dest_port "$cfg" dest_port
    config_get endpoint "$cfg" endpoint
    config_get mode "$cfg" mode
    config_get interval "$cfg" interval
    config_get ping_frequency "$cfg" ping_frequency
    config_get ping_hosts "$cfg" ping_hosts
    config_get no_compress "$cfg" no_compress

    [ -z "$iface" ] || [ -z "$output_type" ] && return

    local args="$iface"

    case "$output_type" in
        tcp)
            args="$args --tcp"
            [ -n "$dest_ip" ] && args="$args --dest-ip=$dest_ip"
            [ -n "$dest_port" ] && args="$args --dest-port=$dest_port"
            ;;
        udp)
            args="$args --udp"
            [ -n "$dest_ip" ] && args="$args --dest-ip=$dest_ip"
            [ -n "$dest_port" ] && args="$args --dest-port=$dest_port"
            ;;
        zmq)
            args="$args --zmq"
            [ -n "$endpoint" ] && args="$args --endpoint=$endpoint"
            [ -n "$mode" ] && args="$args --mode=$mode"
            ;;
        stdout)
            args="$args --stdout"
            ;;
        stderr)
            args="$args --stderr"
            ;;
        *)
            return
            ;;
    esac

    [ -n "$interval" ] && args="$args --interval=$interval"
    [ -n "$count" ] && args="$args --count=$count"
    [ "$no_compress" = "1" ] && args="$args --no-compress"

    [ -n "$ping_frequency" ] && args="$args --ping-frequency=$ping_frequency"

    for p in $ping_hosts; do [ -n "$hosts" ] && hosts="$hosts,$p" || hosts="$p" ; done
    [ -n "$hosts" ] && args="$args --ping-hosts=$hosts"


    instance_name="$iface"
    logger -t iw-telemetry "starting instance $iface with args: $args"

    procd_open_instance
    procd_set_param command "$PROG" $args
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    logger -t iw-telemetry "stopping all iw-telemetry instances"
}


reload_service() {
    logger -t iw-telemetry "reloading $NAME"
    procd_send_signal iw-telemetry HUP
}
